# Generated by Django 5.0.3 on 2024-03-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='mother_name',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
